### ISSUE TITLE
没办法复现，报错

### ISSUE THREAD

**Issue by 592479244** [openmedlab/XrayPULSE#3]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\XrayPULSE-main\demo.py", line 62, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "C:\Users\Administrator\Desktop\XrayPULSE-main\xraypulse\models\xray_pulse.py", line 348, in from_config
    model = cls(
  File "C:\Users\Administrator\Desktop\XrayPULSE-main\xraypulse\models\xray_pulse.py", line 71, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "C:\Users\Administrator\Desktop\XrayPULSE-main\xraypulse\models\blip2.py", line 65, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "C:\Users\Administrator\Desktop\XrayPULSE-main\xraypulse\models\eva_vit.py", line 433, in create_eva_vit_g
    state_dict = torch.load(cached_file, map_location="cpu")
  File "D:\biancheng_soft\conda1\envs\all\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\biancheng_soft\conda1\envs\all\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
是不是缺少了什么配置，或者预训练模型。。

**Comment by zongzi3zz** [comment]
你可以尝试检查网络配饰，或者离线下载预训练模型

**Comment by 592479244** [comment]
eva_clip_g 这个model在哪下载呀，我看他自动下载的model是eva_vit_g.pth  然后就报错了

**Comment by 592479244** [comment]
> 
大哥您好，eva_clip_g 这个model在哪下载呀，我看他自动下载的model是eva_vit_g.pth 然后就报错了

**Comment by zongzi3zz** [comment]
可以用 https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth 进行下载， 然后    将state_dict = torch.load(cached_file, map_location="cpu")修改为state_dict = torch.load(/path_to_eva_vit_g.pth, map_location="cpu")

**Comment by 592479244** [comment]
> 可以用 https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth 进行下载， 然后 将state_dict = torch.load(cached_file, map_location="cpu")修改为state_dict = torch.load(/path_to_eva_vit_g.pth, map_location="cpu")

非常感谢，果然选哟重新从网站自己下载，解决啦，万分感谢！
